package io.github.arnonym.sip

val REASON_PHRASES: Map<Int, String> =
    mapOf(
        // 1xx Provisional
        100 to "Trying",
        180 to "Ringing",
        181 to "Call Is Being Forwarded",
        182 to "Queued",
        183 to "Session Progress",
        199 to "Early Dialog Terminated",
        // 2xx Success
        200 to "OK",
        202 to "Accepted",
        204 to "No Notification",
        // 3xx Redirection
        300 to "Multiple Choices",
        301 to "Moved Permanently",
        302 to "Moved Temporarily",
        305 to "Use Proxy",
        380 to "Alternative Service",
        // 4xx Request Failure
        400 to "Bad Request",
        401 to "Unauthorized",
        402 to "Payment Required",
        403 to "Forbidden",
        404 to "Not Found",
        405 to "Method Not Allowed",
        406 to "Not Acceptable",
        407 to "Proxy Authentication Required",
        408 to "Request Timeout",
        409 to "Conflict",
        410 to "Gone",
        411 to "Length Required",
        412 to "Conditional Request Failed",
        413 to "Request Entity Too Large",
        414 to "Request-URI Too Long",
        415 to "Unsupported Media Type",
        416 to "Unsupported URI Scheme",
        417 to "Unknown Resource-Priority",
        420 to "Bad Extension",
        421 to "Extension Required",
        422 to "Session Interval Too Small",
        423 to "Interval Too Brief",
        424 to "Bad Location Information",
        428 to "Use Identity Header",
        429 to "Provide Referrer Identity",
        430 to "Flow Failed",
        433 to "Anonymity Disallowed",
        436 to "Bad Identity-Info",
        437 to "Unsupported Certificate",
        438 to "Invalid Identity Header",
        439 to "First Hop Lacks Outbound Support",
        440 to "Max-Breadth Exceeded",
        469 to "Bad Info Package",
        470 to "Consent Needed",
        480 to "Temporarily Unavailable",
        481 to "Call/Transaction Does Not Exist",
        482 to "Loop Detected",
        483 to "Too Many Hops",
        484 to "Address Incomplete",
        485 to "Ambiguous",
        486 to "Busy Here",
        487 to "Request Terminated",
        488 to "Not Acceptable Here",
        489 to "Bad Event",
        490 to "Request Updated",
        491 to "Request Pending",
        493 to "Undecipherable",
        494 to "Security Agreement Required",
        // 5xx Server Failure
        500 to "Server Internal Error",
        501 to "Not Implemented",
        502 to "Bad Gateway",
        503 to "Service Unavailable",
        504 to "Server Time-out",
        505 to "Version Not Supported",
        513 to "Message Too Large",
        555 to "Push Notification Service Not Supported",
        580 to "Precondition Failure",
        // 6xx Global Failure
        600 to "Busy Everywhere",
        603 to "Decline",
        604 to "Does Not Exist Anywhere",
        606 to "Not Acceptable",
        607 to "Unwanted",
        608 to "Rejected",
    )
